# Generated by Django 4.0.4 on 2022-06-14 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0027_alter_userprofile_user'),
        ('blog', '0002_alter_comment_text_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.userprofile'),
        ),
    ]
