# Generated by Django 4.0.4 on 2022-06-28 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0031_userinstance'),
        ('blog', '0006_post_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='creator.userprofile'),
        ),
    ]
