# Generated by Django 4.0.4 on 2022-07-04 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_reply_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='author_name',
        ),
        migrations.AlterField(
            model_name='reply',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
