# Generated by Django 4.1.5 on 2023-02-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0003_alter_event_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(default='default.png', height_field=1400, upload_to='poster', width_field=700),
        ),
    ]
