# Generated by Django 4.1.5 on 2023-02-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0007_alter_category_image_alter_event_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(height_field=500, upload_to='images', width_field=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(height_field=1400, upload_to='poster', width_field=700),
        ),
    ]
