# Generated by Django 4.1.7 on 2023-03-18 04:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0013_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='ticket',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
