# Generated by Django 4.1.7 on 2023-03-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0015_alter_guest_options_guest_qr_code_guest_scanned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='qr_code',
            field=models.ImageField(upload_to='qr/'),
        ),
    ]
