# Generated by Django 4.1.7 on 2023-03-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0017_location_venue_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='poster',
            field=models.ImageField(default='default.png', upload_to='poster'),
        ),
    ]
