# Generated by Django 4.1.7 on 2023-03-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0018_venue_description_venue_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=150),
        ),
    ]
