# Generated by Django 4.1.7 on 2023-03-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0019_alter_location_city_alter_location_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
