# Generated by Django 4.1.7 on 2023-03-25 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0020_venue_capacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['city'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('avatar', models.ImageField(upload_to='avatars')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_app.event')),
            ],
            options={
                'verbose_name': 'Speaker',
                'verbose_name_plural': 'Speakers',
            },
        ),
    ]
